// <auto-generated />
namespace SuperShopManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Expense_Category_And_Item_Addedd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Expense_Category_And_Item_Addedd));
        
        string IMigrationMetadata.Id
        {
            get { return "201801161006202_Expense_Category_And_Item_Addedd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
