// <auto-generated />
namespace SuperShopManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ShortDateFormat_Add_And_VM_Table_Deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShortDateFormat_Add_And_VM_Table_Deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201801281917459_ShortDateFormat_Add_And_VM_Table_Deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
